# Generated by Django 5.0.2 on 2024-09-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
