# Generated by Django 5.0.2 on 2024-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
