# Generated by Django 5.0.2 on 2024-09-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0005_profile_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login',
        ),
    ]
