# Generated by Django 5.0.2 on 2024-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_remove_profile_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='exit', upload_to='events_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
