# Generated by Django 5.0.2 on 2024-10-02 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0008_events_event_type_alter_events_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event', 'booking_date')},
        ),
    ]
