# Generated by Django 5.0.2 on 2024-10-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0009_alter_booking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
    ]
