# Generated by Django 5.0.2 on 2024-10-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0010_remove_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default=5.5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=10),
            preserve_default=False,
        ),
    ]
