# Generated by Django 5.0.2 on 2024-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0011_events_location_events_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
