# Generated by Django 5.0.2 on 2024-10-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0012_booking_number_of_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_attendees',
        ),
    ]
