# Generated by Django 5.0.2 on 2024-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0013_remove_booking_number_of_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
