# Generated by Django 5.0.2 on 2024-10-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0014_booking_num_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='feedback',
        ),
    ]
